# Generated by Django 5.0.4 on 2024-05-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='average_response_time',
            field=models.DateField(),
        ),
    ]
